// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,while:66, iterate:70, if:74, else:76}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")SOYQPOOO_QPOOOOQO'#C`'#C`OdQPOOOOQO'#Cb'#CbOiQPO'#CaQOQPOOOqQQO'#CcOOQO'#Co'#CoOiQPO'#CvOOQO'#Cn'#CnOvQPO'#DUOOQO'#Cv'#CvO{QPO,58{O!QQPO,58}OOQO-E6m-E6mOOQO,59b,59bO!VQPO,59pOOQO'#Cm'#CmOOQO1G.g1G.gO![QQO1G.iOdQPO1G/[OdQPO7+$TO!dQPO7+$TO!zQQO'#CfOOQO7+$v7+$vOOQO<<Go<<GoOdQPO<<GoO#RQPO'#CzOOQO'#Ci'#CiOOQO'#Cj'#CjO#WQPO'#DOOOQO'#Ck'#CkOOQO'#Cy'#CyOOQO'#Cp'#CpO#]QQO'#CgO{QPO,59QO#dQPO'#C|O#iQPO'#DQOOQOAN=ZAN=ZO#nQQO,59fO#yQQO,59jOOQO-E6n-E6nOOQO1G.l1G.lO$RQQO,59hO$WQQO,59lOOQO'#C{'#C{OOQO1G/Q1G/QO$]QPO1G/QO$bQPO1G/UO$gQPO1G/SO$lQPO1G/WOOQO7+$l7+$lO!iQQO7+$pO!iQQO7+$nO!iQQO7+$rOOQO<<H[<<H[OOQO<<HY<<HYO$qQQO<<H^OOQO'#Cl'#ClO!iQQOAN=xOOQOG23dG23d",
  stateData: "%Y~OgOSPOS~ORPO~OhQO~OiSO~OWVOhYO~OX^O~OkaO~OwbO~OkdO~OleO~OXgOlfO~OlkO~OXlOiSOqmOsnOupO~OwZP~P!iOkxO~OkyO~OwZX~P!iOk|O~Ok}O~OX!OO[!OOl!PO~OX!OO[!OO~OX!SO~OX!TO~Ol!UO~Ol!VO~Ol!WO~Ol!XO~Ov!]OXtyityqtystyutywty~O",
  goto: "$tyPPPPz}!Q!`PP!d!uP!x#Q#Y#b#e#k#o#uPPPPP#{PP$O$`$h$`P$`P$`PPP$nRRPRURQTRchefhks!V!W!X!^TWTXQieQjf[qhs!V!W!X!^RwkRth]uhs!V!W!X!^]ohs!V!W!X!^]vhs!V!W!X!^R!^![Qc]R{tTZTXQXTR_XQshRzsR]TSrhsQ!Y!VQ!Z!WQ![!XR!_!^]qhs!V!W!X!^Q!QxR!RyQ[TR`X",
  nodeNames: "⚠ Comment Script Class ProgramClass ScriptBlock Start Function Define Identifier Block InnerBlock Number While Iterate If Else End ProgramMain",
  maxTerm: 40,
  nodeProps: [
    ["closedBy", 6,"End"],
    ["openedBy", 17,"Start"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "/W~RiX^!ppq!pxy#eyz#j!P!Q#o!Q![$^!c!}$f#T#V$f#V#W$w#W#X'X#X#d$f#d#e*T#e#j$f#j#k-e#k#o$f#o#p.|#q#r/R#y#z!p$f$g!p#BY#BZ!p$IS$I_!p$I|$JO!p$JT$JU!p$KV$KW!p&FU&FV!p~!uYg~X^!ppq!p#y#z!p$f$g!p#BY#BZ!p$IS$I_!p$I|$JO!p$JT$JU!p$KV$KW!p&FU&FV!p~#jOk~~#oOl~~#rP!P!Q#u~#zSP~OY#uZ;'S#u;'S;=`$W<%lO#u~$ZP;=`<%l#u~$cP[~!Q![$^Q$kSXQ!Q![$f!c!}$f#R#S$f#T#o$fR$|UXQ!Q![$f!c!}$f#R#S$f#T#`$f#`#a%`#a#o$fR%eTXQ!Q![$f!c!}$f#R#S$f#T#U%t#U#o$fR%yUXQ!Q![$f!c!}$f#R#S$f#T#g$f#g#h&]#h#o$fR&bUXQ!Q![$f!c!}$f#R#S$f#T#g$f#g#h&t#h#o$fR&{SRPXQ!Q![$f!c!}$f#R#S$f#T#o$fR'^UXQ!Q![$f!c!}$f#R#S$f#T#X$f#X#Y'p#Y#o$fR'uUXQ!Q![$f!c!}$f#R#S$f#T#Y$f#Y#Z(X#Z#o$fR(^UXQ!Q![$f!c!}$f#R#S$f#T#]$f#]#^(p#^#o$fR(uUXQ!Q![$f!c!}$f#R#S$f#T#b$f#b#c)X#c#o$fR)^UXQ!Q![$f!c!}$f#R#S$f#T#X$f#X#Y)p#Y#o$fR)wSWPXQ!Q![$f!c!}$f#R#S$f#T#o$fR*YUXQ!Q![$f!c!}$f#R#S$f#T#f$f#f#g*l#g#o$fR*qUXQ!Q![$f!c!}$f#R#S$f#T#c$f#c#d+T#d#o$fR+YUXQ!Q![$f!c!}$f#R#S$f#T#Z$f#Z#[+l#[#o$fR+qUXQ!Q![$f!c!}$f#R#S$f#T#f$f#f#g,T#g#o$fR,YTXQ!Q![$f!c!}$f#R#S$f#T#U,i#U#o$fR,nUXQ!Q![$f!c!}$f#R#S$f#T#a$f#a#b-Q#b#o$fR-XSXQhP!Q![$f!c!}$f#R#S$f#T#o$fR-jUXQ!Q![$f!c!}$f#R#S$f#T#c$f#c#d-|#d#o$fR.RUXQ!Q![$f!c!}$f#R#S$f#T#]$f#]#^.e#^#o$fR.jUXQ!Q![$f!c!}$f#R#S$f#T#W$f#W#X)p#X#o$f~/ROi~~/WOw~",
  tokenizers: [0, 1],
  topRules: {"Script":[0,2]},
  specialized: [{term: 9, get: value => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
