// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,"iniciar-programa":52, "inicia-ejecucion":54, mientras:68, "si-es-cero":74, "junto-a-zumbador":76, "no-junto-a-zumbador":78, "frente-libre":80, "izquierda-libre":82, "derecha-libre":84, "frente-bloqueado":86, "izquierda-bloqueada":88, "derecha-bloqueada":90, "orientado-al-norte":92, "orientado-al-sur":94, "orientado-al-este":96, "orientado-al-oeste":98, "no-orientado-al-norte":100, "no-orientado-al-sur":102, "no-orientado-al-este":104, "no-orientado-al-oeste":106, "algun-zumbador-en-la-mochila":108, "ningun-zumbador-en-la-mochila":110, o:114, y:116, no:118, hacer:120, repetir:124, veces:126, si:130, entonces:132, inicio:134, fin:136, "termina-ejecucion":140, "finalizar-programa":142}
export const parser = LRParser.deserialize({
  version: 14,
  states: "(|OVQPOOOOQO'#C^'#C^O[QPOOOOQO'#Ca'#CaOaQPO'#C`OrQPOOOwQPO'#CzOOQO'#Cc'#CcO!VQPO'#C}OOQO'#Cj'#CjOOQO'#Cl'#ClO!VQPO'#DnO#jQPO'#CnOOQO'#Cy'#CyOOQO'#Cx'#CxO#qQPO,58zO#yQPO'#DkOOQO'#Co'#CoOOQO'#Cr'#CrQOQPOOO$OQPO,59fOOQO'#Ce'#CeOOQO'#DQ'#DQO!VQPO'#DQOOQO'#Ch'#ChOOQO'#DP'#DPO$TQPO,59iO!VQPO'#DPO$`QPO'#CdO$eQPO,5:YOOQO,59Y,59YO$pQPO,59YOOQO'#Cp'#CpO$xQPO,59dOOQO'#Cq'#CqOOQO1G.f1G.fO%VQPO,5:VO%[QPO1G/QO%aQPO,59lOOQO'#Cf'#CfOOQO'#Cg'#CgOOQO'#Df'#DfO!VQPO,59kOOQO'#Ci'#CiOaQPO1G/TO%lQPO,59kO%}QPO,59OOOQO'#Cm'#CmOaQPO1G/tOOQO1G.t1G.tOOQO1G/O1G/OOOQO'#Ck'#CkOaQPO1G/qOOQO7+$l7+$lOOQO1G/W1G/WOOQO1G/V1G/VOOQO7+$o7+$oO&SQPO1G.jOOQO7+%`7+%`OOQO7+%]7+%]OOQO7+$U7+$U",
  stateData: "&X~OiOS~OjPO~OkRO~ORUOrVO!`XO!cYO!eaO~O!ibO~OodO!gnX!hnX!fnX~OogOulOveOweOxeOyeOzeO{eO|eO}eO!OeO!PeO!QeO!ReO!SeO!TeO!UeO!VeO!WeO!XeO!]hO~O!fpO~PaO!gqO!hrO~OUtO~OUuO~O!ZwO![xO!^{O~Oo!OO~O!ZwO![xO!d!PO~O!fpO!gqO~O!gla!hla!fla~PaO!a!TO~Op!VO~Op!WO!ZwO![xO~O!ZwO![xO!^sa!dsapsa~OU!ZO~Op!^O~O",
  goto: "%f!cPP!dP!g!jP!m!u!u!|!|#S#Z#^#f#i#q#t#|$U$[$_PPPPP$b$h#tPP#tP$x%XPPPPPPPPPPPPPPPPPPP%`PPPP#tPP#tRQORTQRSQ]WS[q|!Q!UZfWZgkzXyjmv}ZkWZgkzR|j]`S[q|!Q!UR!Ut]ZS[q|!Q!UR!Qm]]S[q|!Q!U][S[q|!Q!UQn[R!RoRs_RcTQ_SRo[S^S[Q!SqQ!Y|Q![!QR!]!UQjWQmZQvgQ}kR!XzZiWZgkzXzjmv}",
  nodeNames: "⚠ Script StartProgram Identifier Execution StartExecution Number While IFZ BoolFunc Or And Not Do Iterate Times If Then Block Begin End EndExecution EndProgram",
  maxTerm: 71,
  nodeProps: [
    ["closedBy", 19,"End"],
    ["openedBy", 20,"Begin"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "$[~RdX^!apq!axy#Uyz#Z!Q![#`!]!^#h!c!}#m#R#S#m#T#o#m#y#z!a$f$g!a%W%o#m%p&a#m&b&j#m#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~!fYi~X^!apq!a#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~#ZOo~~#`Op~~#ePU~!Q![#`~#mO!g~~#rWR~}!O#m!Q![#m!c!}#m#R#S#m#T#o#m%W%o#m%p&a#m&b&j#m",
  tokenizers: [0],
  topRules: {"Script":[0,1]},
  specialized: [{term: 3, get: value => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
