// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Script = 2,
  Class = 3,
  Program = 4,
  Define = 5,
  Identifier = 6,
  Block = 7,
  Number = 8
