// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Script = 1,
  StartProgram = 2,
  Identifier = 3,
  Execution = 4,
  StartExecution = 5,
  Number = 6,
  While = 7,
  Do = 8,
  Iterate = 9,
  Times = 10,
  If = 11,
  Then = 12,
  Block = 13,
  Begin = 14,
  End = 15,
  EndExecution = 16,
  EndProgram = 17
