// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Script = 2,
  Class = 3,
  ProgramClass = 4,
  ScriptBlock = 5,
  Start = 6,
  Function = 7,
  Define = 8,
  Identifier = 9,
  Block = 10,
  InnerBlock = 11,
  Number = 12,
  While = 13,
  Iterate = 14,
  End = 15,
  ProgramMain = 16
