// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
const spec_Identifier = {__proto__:null,"iniciar-programa":90, "define-nueva-instruccion":92, como:94, avanza:100, "gira-izquierda":102, "deja-zumbador":104, "coge-zumbador":106, apagate:108, mientras:116, "si-es-cero":122, "junto-a-zumbador":124, "no-junto-a-zumbador":126, "frente-libre":128, "izquierda-libre":130, "derecha-libre":132, "frente-bloqueado":134, "izquierda-bloqueada":136, "derecha-bloqueada":138, "orientado-al-norte":140, "orientado-al-sur":142, "orientado-al-este":144, "orientado-al-oeste":146, "no-orientado-al-norte":148, "no-orientado-al-sur":150, "no-orientado-al-este":152, "no-orientado-al-oeste":154, "algun-zumbador-en-la-mochila":156, "ningun-zumbador-en-la-mochila":158, o:162, y:164, no:166, hacer:168, repetir:172, veces:174, si:178, entonces:180, inicio:182, fin:184, "define-prototipo-instruccion":190, "inicia-ejecucion":192, "termina-ejecucion":194, "finalizar-programa":196}
export const parser = LRParser.deserialize({
  version: 14,
  states: "-hO]QPOOPbOPOOOOQO'#C`'#C`OjQPOOPuOQO'#C]P!QOSO'#C^POOO)C>u)C>uOOQO'#Cc'#CcO!]QPO'#CbOOQO'#Cv'#CvO!bQPO'#CuOOQO'#C}'#C}OjQPOOOOQO'#Cx'#CxO!gQPO'#CwO#XQPOOPOOO'#C{'#C{P#^OQO,58wPOOO,58w,58wPOOO'#C|'#C|P#iOSO,58xPOOO,58x,58xO#tQPO,58|O#|QPO,59aOOQO-E6{-E6{OOQO'#Ce'#CeOOQO'#D_'#D_O$RQPO'#D_OOQO'#Cg'#CgO$jQPO'#DgOOQO'#Cn'#CnOOQO'#Cp'#CpO$jQPO'#EWOOQO'#E]'#E]O%}QPO,59cO&VQPO'#CrOOQO'#D^'#D^O&^QPO'#ETOOQO'#Cs'#CsOOQO'#Cz'#CzQOQPOOPOOO-E6y-E6yPOOO1G.c1G.cPOOO-E6z-E6zPOOO1G.d1G.dOOQO'#Cd'#CdO!gQPO1G.hO&cQPO1G.hOOQO1G.{1G.{O&hQPO,59yOOQO'#Ci'#CiOOQO'#Dj'#DjO$jQPO'#DjOOQO'#Cl'#ClOOQO'#Di'#DiO&mQPO,5:RO$jQPO'#DiO&xQPO'#ChO&}QPO,5:rO'YQPO,5:wOOQO'#Cy'#CyOOQO1G.}1G.}O'gQPO,59^OOQO,59^,59^OOQO'#Ct'#CtO'oQPO,5:oOOQO7+$S7+$SO'tQPO7+$SO'yQPO1G/eO(OQPO,5:UOOQO'#Cj'#CjOOQO'#Ck'#CkOOQO'#EO'#EOO$jQPO,5:TOOQO'#Cm'#CmO!gQPO1G/mO(ZQPO,5:TO(lQPO,59SOOQO'#Cq'#CqO!gQPO1G0^OOQO1G0c1G0cOOQO1G.x1G.xOOQO'#Co'#CoO!gQPO1G0ZO(qQPO<<GnOOQO7+%P7+%POOQO1G/p1G/pOOQO1G/o1G/oOOQO7+%X7+%XO(vQPO1G.nOOQO7+%x7+%xOOQO7+%u7+%uO!gQPOAN=YOOQO7+$Y7+$YO({QPOG22tOOQOLD(`LD(`",
  stateData: ")Q~OtOSuPQyPQ~O}QO~OuSOyTO~O!OVO#RXO#S]O~Ov`Ow`OxbO~OzcO{cO|eO~OTfO~OTgO~OTkO!SiO!TiO!UiO!ViO!WiO![lO!xnO!{oO!}vO~O#UwO~Ov`Ow`OxzO~OzcO{cO||O~O!P}O!X!PO~O#Q!QO~O!X!RO#Q!RX#T!RX#O!RX!O!RX#R!RX#S!RX~O!X!UO!_!ZO!`!SO!a!SO!b!SO!c!SO!d!SO!e!SO!f!SO!g!SO!h!SO!i!SO!j!SO!k!SO!l!SO!m!SO!n!SO!o!SO!p!SO!q!SO!u!VO~O#Q!]O#T!^O~O#O!bO~P!gOY!cO~OT!eO~OY!fO~O!s!hO!t!iO!v!lO~O!X!oO~O!s!hO!t!iO!|!pO~O#Q#Pa#T#Pa#O#Pa~P!gO#O!bO#Q!]O~O!y!tO~O!Y!vO~O!Y!wO~O!Y!xO!s!hO!t!iO~O!s!hO!t!iO!v!]a!|!]a!Y!]a~OY!{O~O!P}O~O!Y#PO~O#Q#RO~O",
  goto: "'j#QP#R#RP#UP#X#]#a#gP#q#{#{$S$S$Y$a$d$n$q${%O%Y%d#X%j%n%r%v%y%|&S&YPPPPPPPPPPPPPP&`%OPPPPPPP%OP&v'VPPPPPPPPPPPPPPPPPPP'^PPPP%OPP%OPPPP'dRUPRROTZR[TWR[Q!OfR#O!vaj^s!O!]!m!q!u#Oam^s!O!]!m!q!u#OZ!Tmp!U!Y!kX!j!X![!g!nZ!Ymp!U!Y!kR!m!Xau^s!O!]!m!q!u#OR!u!cap^s!O!]!m!q!u#OR!q![at^s!O!]!m!q!u#Oas^s!O!]!m!q!u#OQ!asR!s!`TYR[T_R[T^R[R!_rRx_QaSRyaQdTR{dQ[RRh[Sq^sQ!d!OQ!r!]Q!z!mQ!|!qQ!}!uR#Q#OQ!XmQ![pQ!g!UQ!n!YR!y!kZ!Wmp!U!Y!kX!k!X![!g!nQr^R!`s",
  nodeNames: "⚠ BlockComment BlockComment2 Script StartProgram Identifier Function Define As BuiltIn Number While IFZ BoolFunc Or And Not Do Iterate Times If Then Block Begin End Prototype Prototipo Execution StartExecution EndExecution EndProgram",
  maxTerm: 98,
  nodeProps: [
    ["closedBy", 23,"End"],
    ["openedBy", 24,"Begin"]
  ],
  skippedNodes: [0,1,2,31,32],
  repeatNodeCount: 3,
  tokenData: "$l~ReX^!dpq!dxy#Xyz#f!Q![#k!]!^#s!c!}#x#R#S#x#T#o#x#o#p$g#y#z!d$f$g!d%W%o#x%p&a#x&b&j#x#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~!iYt~X^!dpq!d#y#z!d$f$g!d#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~#^P!X~z{#a~#fOy~~#kO!Y~~#pPY~!Q![#k~#xO#Q~~#}WT~}!O#x!Q![#x!c!}#x#R#S#x#T#o#x%W%o#x%p&a#x&b&j#x~$lOu~",
  tokenizers: [2, new LocalTokenGroup("d~RQYZX#q#r^~^Ow~~cOx~~", 19, 38), new LocalTokenGroup("j~RQYZXz{^~^O{~~aPyzd~iO|~~", 25, 42)],
  topRules: {"Script":[0,3]},
  specialized: [{term: 5, get: value => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
