// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
const spec_Identifier = {__proto__:null,"iniciar-programa":76, "inicia-ejecucion":78, mientras:92, "si-es-cero":98, "junto-a-zumbador":100, "no-junto-a-zumbador":102, "frente-libre":104, "izquierda-libre":106, "derecha-libre":108, "frente-bloqueado":110, "izquierda-bloqueada":112, "derecha-bloqueada":114, "orientado-al-norte":116, "orientado-al-sur":118, "orientado-al-este":120, "orientado-al-oeste":122, "no-orientado-al-norte":124, "no-orientado-al-sur":126, "no-orientado-al-este":128, "no-orientado-al-oeste":130, "algun-zumbador-en-la-mochila":132, "ningun-zumbador-en-la-mochila":134, o:138, y:140, no:142, hacer:144, repetir:148, veces:150, si:154, entonces:156, inicio:158, fin:160, "termina-ejecucion":164, "finalizar-programa":166}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*tO]QPOOPbOPOOOOQO'#C`'#C`OjQPOOPoOQO'#C]PzOSO'#C^POOO)C>n)C>nOOQO'#Cc'#CcO!VQPO'#CbO!hQPOOPOOO'#Cu'#CuP!mOQO,58wPOOO,58w,58wPOOO'#Cv'#CvP!xOSO,58xPOOO,58x,58xO#TQPO'#DWOOQO'#Ce'#CeO#cQPO'#DZOOQO'#Cl'#ClOOQO'#Cn'#CnO#cQPO'#DzO$vQPO'#CpOOQO'#DV'#DVOOQO'#DU'#DUO$}QPO,58|O%VQPO'#DwOOQO'#Cq'#CqOOQO'#Ct'#CtQOQPOOPOOO-E6s-E6sPOOO1G.c1G.cPOOO-E6t-E6tPOOO1G.d1G.dO%[QPO,59rOOQO'#Cg'#CgOOQO'#D^'#D^O#cQPO'#D^OOQO'#Cj'#CjOOQO'#D]'#D]O%aQPO,59uO#cQPO'#D]O%lQPO'#CfO%qQPO,5:fOOQO,59[,59[O%|QPO,59[OOQO'#Cr'#CrO&UQPO,59pOOQO'#Cs'#CsOOQO1G.h1G.hO&cQPO,5:cO&hQPO1G/^O&mQPO,59xOOQO'#Ch'#ChOOQO'#Ci'#CiOOQO'#Dr'#DrO#cQPO,59wOOQO'#Ck'#CkO!VQPO1G/aO&xQPO,59wO'ZQPO,59QOOQO'#Co'#CoO!VQPO1G0QOOQO1G.v1G.vOOQO1G/[1G/[OOQO'#Cm'#CmO!VQPO1G/}OOQO7+$x7+$xOOQO1G/d1G/dOOQO1G/c1G/cOOQO7+${7+${O'`QPO1G.lOOQO7+%l7+%lOOQO7+%i7+%iOOQO7+$W7+$W",
  stateData: "'e~OmOSnPQrPQ~OvQO~OnSOrTO~OwVO~OoYOpYOq[O~Os]Ot]Ou_O~OT`O!OaO!lcO!odO!qkO~O!ulO~OoYOpYOqoO~Os]Ot]OuqO~O{rO!szX!tzX!rzX~O{uO!RzO!SsO!TsO!UsO!VsO!WsO!XsO!YsO!ZsO![sO!]sO!^sO!_sO!`sO!asO!bsO!csO!dsO!esO!ivO~O!r!OO~P!VO!s!PO!t!QO~OW!SO~OW!TO~O!g!VO!h!WO!j!ZO~O{!^O~O!g!VO!h!WO!p!_O~O!r!OO!s!PO~O!sxa!txa!rxa~P!VO!m!cO~O|!eO~O|!fO!g!VO!h!WO~O!g!VO!h!WO!j!Pa!p!Pa|!Pa~OW!iO~O|!lO~O",
  goto: "&R!oP!p!pP!sP!v!yP!|#U#U#]#]#c#j#m#u#x$Q$T$]$e$k$n$q$wPPPPPPPPPPPPP$}%T$TPP$TP%e%tPPPPPPPPPPPPPPPPPPP%{PPPP$TPP$TRUPRRORXRRWR]bWf!P![!`!dZtbeuy!YX!Xx{!U!]Zybeuy!YR![x]jWf!P![!`!dR!d!S]eWf!P![!`!dR!`{]gWf!P![!`!d]fWf!P![!`!dQ|fR!a}R!RiRmXQZSRnZQ^TRp^QiWR}fShWfQ!b!PQ!h![Q!j!`R!k!dQxbQ{eQ!UuQ!]yR!g!YZwbeuy!YX!Yx{!U!]",
  nodeNames: "⚠ BlockComment BlockComment2 Script StartProgram Identifier Execution StartExecution Number While IFZ BoolFunc Or And Not Do Iterate Times If Then Block Begin End EndExecution EndProgram",
  maxTerm: 83,
  nodeProps: [
    ["closedBy", 21,"End"],
    ["openedBy", 22,"Begin"]
  ],
  skippedNodes: [0,1,2,25,26],
  repeatNodeCount: 2,
  tokenData: "$l~ReX^!dpq!dxy#Xyz#f!Q![#k!]!^#s!c!}#x#R#S#x#T#o#x#o#p$g#y#z!d$f$g!d%W%o#x%p&a#x&b&j#x#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~!iYm~X^!dpq!d#y#z!d$f$g!d#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~#^P{~z{#a~#fOr~~#kO|~~#pPW~!Q![#k~#xO!s~~#}WT~}!O#x!Q![#x!c!}#x#R#S#x#T#o#x%W%o#x%p&a#x&b&j#x~$lOn~",
  tokenizers: [2, new LocalTokenGroup("d~RQYZX#q#r^~^Op~~cOq~~", 19, 31), new LocalTokenGroup("j~RQYZXz{^~^Ot~~aPyzd~iOu~~", 25, 35)],
  topRules: {"Script":[0,3]},
  specialized: [{term: 5, get: value => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
