// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%pOYQPOOO_QPOOOdQPOOOiQQOOOqQSO'#CmOOQO'#Ce'#CeOiQQO'#ClOvQPO'#CsOOQO'#Cl'#ClO{QPOOO!QQPO,59XOOQO-E6c-E6cOOQO,59W,59WO!VQPO,59_QOQPOOO![QSO1G.sO!dQPO1G.yO!dQPO7+$_O!iQPO7+$_O!nQSO'#CcOOQO7+$e7+$eOOQO<<Gy<<GyO!dQPO<<GyO!yQPO'#CqOOQO'#Cp'#CpOOQO'#Cf'#CfO#OQSO,58}OOQO,58},58}OOQOAN=eAN=eO#ZQSO,59]OOQO-E6d-E6dOOQO1G.i1G.iOOQO'#Cr'#CrOOQO1G.w1G.wO#fQPO1G.wOOQO7+$c7+$c",
  stateData: "#k~O]OSPOS~ORPO~OSQO~O_RO~OTSOhVO~OUYO~Ob]O~O^^O~Ob_O~Oc`O~OUbOcaO~O_cO~OcfO~OUgO^kO_cO~ObmO~OUgO^oO_cO~OUpOWpOcqO~OcsO~O",
  goto: "!lhPPPPPPPiPv|PPPPP!S!VPP!Z!_!c!fQd`QeaShcjRlfQURRZUQjcRnjRXRTTRUTicjThcjRrmQWRR[U",
  nodeNames: "⚠ Comment Script Class Program Define Identifier Block Number",
  maxTerm: 24,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "/Y~RiX^!ppq!pxy#eyz#j!P!Q#o!Q![$^!c!}$f#T#V$f#V#W$w#W#X'X#X#d$f#d#e*T#e#j$f#j#k-g#k#o$f#o#p/O#q#r/T#y#z!p$f$g!p#BY#BZ!p$IS$I_!p$I|$JO!p$JT$JU!p$KV$KW!p&FU&FV!p~!uY]~X^!ppq!p#y#z!p$f$g!p#BY#BZ!p$IS$I_!p$I|$JO!p$JT$JU!p$KV$KW!p&FU&FV!p~#jOb~~#oOc~~#rP!P!Q#u~#zSP~OY#uZ;'S#u;'S;=`$W<%lO#u~$ZP;=`<%l#u~$cPW~!Q![$^S$kSUS!Q![$f!c!}$f#R#S$f#T#o$fT$|UUS!Q![$f!c!}$f#R#S$f#T#`$f#`#a%`#a#o$fT%eTUS!Q![$f!c!}$f#R#S$f#T#U%t#U#o$fT%yUUS!Q![$f!c!}$f#R#S$f#T#g$f#g#h&]#h#o$fT&bUUS!Q![$f!c!}$f#R#S$f#T#g$f#g#h&t#h#o$fT&{SRPUS!Q![$f!c!}$f#R#S$f#T#o$fU'^UUS!Q![$f!c!}$f#R#S$f#T#X$f#X#Y'p#Y#o$fU'uUUS!Q![$f!c!}$f#R#S$f#T#Y$f#Y#Z(X#Z#o$fU(^UUS!Q![$f!c!}$f#R#S$f#T#]$f#]#^(p#^#o$fU(uUUS!Q![$f!c!}$f#R#S$f#T#b$f#b#c)X#c#o$fU)^UUS!Q![$f!c!}$f#R#S$f#T#X$f#X#Y)p#Y#o$fU)wSTQUS!Q![$f!c!}$f#R#S$f#T#o$fV*YUUS!Q![$f!c!}$f#R#S$f#T#f$f#f#g*l#g#o$fV*qUUS!Q![$f!c!}$f#R#S$f#T#c$f#c#d+T#d#o$fV+YUUS!Q![$f!c!}$f#R#S$f#T#Z$f#Z#[+l#[#o$fV+qUUS!Q![$f!c!}$f#R#S$f#T#f$f#f#g,T#g#o$fV,YTUS!Q![$f!c!}$f#R#S$f#T#U,i#U#o$fV,nUUS!Q![$f!c!}$f#R#S$f#T#a$f#a#b-Q#b#o$fV-ZShQUSSP!Q![$f!c!}$f#R#S$f#T#o$fU-lUUS!Q![$f!c!}$f#R#S$f#T#c$f#c#d.O#d#o$fU.TUUS!Q![$f!c!}$f#R#S$f#T#]$f#]#^.g#^#o$fU.lUUS!Q![$f!c!}$f#R#S$f#T#W$f#W#X)p#X#o$f~/TO_~~/YO^~",
  tokenizers: [0, 1, 2],
  topRules: {"Script":[0,2]},
  tokenPrec: 0
})
