// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Script = 2,
  Class = 3,
  Program = 4,
  Start = 5,
  Define = 6,
  Identifier = 7,
  Block = 8,
  InnerBlock = 9,
  Number = 10,
  End = 11
